name: Build MagShare

on:
  push:
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Qt and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y qtbase5-dev qttools5-dev-tools qtmultimedia5-dev \
            libqt5x11extras5-dev libxcb1-dev libxcb-screensaver0-dev libx11-dev \
            build-essential debhelper devscripts fakeroot

      - name: Build application
        run: |
          qmake magshare-desktop.pro
          make -j$(nproc)

      - name: Create .deb package
        run: |
          mkdir -p debian/magshare/usr/bin
          mkdir -p debian/magshare/usr/share/applications
          mkdir -p debian/magshare/usr/share/pixmaps
          mkdir -p debian/magshare/DEBIAN

          # Copy binary
          cp test/magshare debian/magshare/usr/bin/
          chmod +x debian/magshare/usr/bin/magshare

          # Copy icon
          cp src/images/magshare.png debian/magshare/usr/share/pixmaps/magshare.png

          # Create .desktop entry
          cat > debian/magshare/usr/share/applications/magshare.desktop << EOF
          [Desktop Entry]
          Version=1.0
          Type=Application
          Name=MagShare
          Comment=Secure LAN Messenger and File Sharing
          Exec=magshare
          Icon=magshare
          Terminal=false
          Categories=Network;InstantMessaging;
          EOF

          # Create control file
          cat > debian/magshare/DEBIAN/control << EOF
          Package: magshare
          Version: 1.1.2
          Section: net
          Priority: optional
          Architecture: amd64
          Depends: libqt5core5a, libqt5gui5, libqt5widgets5, libqt5network5, libqt5multimedia5
          Maintainer: MagShare Team <team@magshare.net>
          Description: Secure LAN Messenger and File Sharing
           MagShare is a secure peer-to-peer messenger and file sharing application
           designed for local area networks.
          EOF

          # Build .deb package
          dpkg-deb --build debian/magshare
          mv debian/magshare.deb magshare_1.1.2_amd64.deb

      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: magshare-linux
          path: |
            magshare_1.1.2_amd64.deb
            test/magshare

  
  create-release:
    needs: [build-linux]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            magshare-linux/magshare_1.1.2_amd64.deb
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
